# fly.toml app configuration file generated for express-ecommerce-admin on 2023-12-22T19:44:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "express-ecommerce-admin"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
